spring:
  datasource:
    url: jdbc:mysql://localhost:3306/japan?serverTimezone=Europe/Warsaw&useSSL=False&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

security:
  jwt:
    token:
      secret-key: secretKey
